---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    self_contained: true
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```


```{r}
data("ny_noaa")

ny_noaa = 
  ny_noaa %>% 
  filter(date >= "2008-01-01" & date <= "2010-12-31", id %in% c("USC00302454", "USC00300785", "USC00308944"))%>% 
  drop_na() %>% 
    mutate(
    year = lubridate::year(date),
    month = lubridate::month(date),
    tmin = as.numeric(tmin),
    tmax = as.numeric(tmax),
    id = case_when(
      id == "USC00302454" ~ "East Sidney, NY",
      id == "USC00300785" ~ "Boonville, NY",
      id == "USC00308944" ~ "Wanakena Ranger School, NY")
)
    
ny_noaa = 
  ny_noaa %>% 
  mutate(
    tmin = tmin/10,
    tmax = tmax/10, 
    prcp = prcp/10,
  )
```

Column {data-width=600}
-----------------------------------------------------------------------

### Lineplot

```{r}
  ny_noaa %>% 
  mutate(
    year_month = floor_date(date, "month")) %>%
  group_by(id, year_month) %>%
  summarize(
    mean_prcp = mean(prcp)) %>%
  plot_ly(
    x = ~year_month, y = ~mean_prcp, color = ~id,
    type = "scatter", mode = "lines", colors = "viridis"
  ) %>%
  layout(
    title = "Monthly Average Precipitation Over Time by Station",
    xaxis = list(title = "Date"),
    yaxis = list(title = "Monthly Average Precipitation (inches)"),
    legend = list(title = list(text = "Station ID"))
  )
```

Column {data-width=400}
-----------------------------------------------------------------------

### Boxplot

```{r}
ny_noaa %>%
  plot_ly(
    x = ~year, y = ~tmax, color = ~id,
    type = "box", colors = "viridis"
  )%>%
layout(
    title = list(
      text = "Distribution of Maximum Temperatures from 2005-2010 for Three NY Monitors",
      font = list(size = 12)
    ), 
    boxmode = "group",
xaxis = list(
    title = "Year",
    tickvals = unique(ny_noaa$year)),
    yaxis = list(title = "Maximum Temps Degrees C")
  )
```

### Histogram

```{r}
ny_noaa %>% 
  filter(year >= 2009) %>% 
  plot_ly(
    x = ~tmin, color = ~id,
  type = "histogram", 
  mode = "markers", 
  alpha = 0.5, 
  colors = "viridis"
  )%>%
  layout(
    title = list(
      text = "Frequency of Minimum Temperature in 2009 and 2010 for three NY Monitors",
      font = list(size = 12) 
    ),
    xaxis = list(
      title = "Minimum Temps in Degrees C", 
      range = c(min(ny_noaa$tmin), 30)
    ),
    yaxis = list(
      title = "Frequency")
  )
```

