---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

### Here are some plots

today' we're making interacive plots in plotly. we'll make examples using the NYC airbnb dataset.

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Do some initial data cleaning/subsetting.
```{r}
data("ny_noaa")

ny_noaa = 
  ny_noaa %>% 
  filter(date >= "2008-01-01" & date <= "2010-12-31", id %in% c("USC00302454", "USC00300785", "USC00308944"))%>% 
  drop_na() %>% 
    mutate(
    year = lubridate::year(date),
    month = lubridate::month(date),
    tmin = as.numeric(tmin),
    tmax = as.numeric(tmax),
    id = case_when(
      id == "USC00302454" ~ "East Sidney, NY",
      id == "USC00300785" ~ "Boonville, NY",
      id == "USC00308944" ~ "Wanakena Ranger School, NY")
  )

	
#USC00300785 Boonville, NY
#USC00302454 East Sidney, NY
#USC00308944 Wanakena Ranger School, NY

set.seed(123)
selected_stations = sample(unique(ny_noaa$id), 3)
view(selected_stations)

```

Histogram
```{r}

ny_noaa %>% 
  filter(year >= 2009) %>% 
  plot_ly(
    x = ~tmin, color = ~id,
  type = "histogram", mode = "markers", alpha = 0.5, colors = "viridis"
  )
```

Boxplot
```{r}
ny_noaa %>%
  plot_ly(
    x = ~year, y = ~tmax, color = ~id,
    type = "box", colors = "viridis"
  )%>%
  layout(
    title = "Distribution of Maximum Temperature from 2005-2010 for three NY Monitors", 
    boxmode = "group",
xaxis = list(
    title = "Year",
    tickvals = unique(ny_noaa$year)),
    yaxis = list(title = "Maximum Temperature")
  )
```


Lineplot
```{r}

ny_noaa %>% 
  mutate(
    year_month = floor_date(date, "month")) %>%
  group_by(id, year_month) %>%
  summarize(
    mean_prcp = mean(prcp)) %>%
  plot_ly(
    x = ~year_month, y = ~mean_prcp, color = ~id,
    type = "scatter", mode = "lines", colors = "viridis"
  ) %>%
  layout(
    title = "Monthly Average Precipitation Over Time by Station",
    xaxis = list(title = "Date"),
    yaxis = list(title = "Monthly Average Precipitation (inches)"),
    legend = list(title = list(text = "Station ID"))
  )

```

